---
title: "Omnibenchmark backend comparison"
date: "`r format(Sys.time(), '%d %B, %Y %H:%M:%S')`"
output:
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
    code_download: true
    number_sections: true
    df_print: kable
    theme: lumen
params:
    performance_bn: "performance-results.rds" # the performance basenames as generated by `04_metric_collector.Rmd` 
    metrics_bn: "metrics-results.rds"         # these are ignored in this report
    clustering_dir: ""                        # the path containing all `out` ob folders
editor_options: 
  chunk_output_type: console
---


```{r}
library(dplyr)
library(ggplot2)
library(knitr)
```

`bn` stands for basename (e.g. the RDS basenames generated by `04_metric_collector.Rmd`) and `clustering_dir` stands for the parent directory with all `out_conda`, `out_singularity` etc dirs. 

This report aims to generalize https://github.com/imallona/clustering_report/blob/6b4765d081f8882c7f7f40bf85fddefc02c1c7f2/quick-dirty-analysis.R

```
rmarkdown::render("08_performances_across_backends.Rmd", params = list(
  performance_bn = "performance-results.rds",
  metrics_bn = "metrics-results.rds",
  clustering_dir =  "/home/imallona/src/clustering_example"))
```

```{r}
opts_chunk$set(fig.width = 6,
               fig.height = 6,
               cache = FALSE,
               include = TRUE,
               dev = "png",
               cache.lazy = FALSE,
               warning = TRUE,
               message = TRUE)
```

```{r}
## this will get as many performance/metrics files as runs there were
## params <- list(performance_bn = "performance-results.rds",
##                metrics_bn = "metrics-results.rds",
##                clustering_dir =  "/home/imallona/src/clustering_example")

(runs <- list.files(pattern = params$performance_bn, path = params$clustering_dir, recursive = TRUE))


```


# Pairwise compare {.tabset .tabset-pills}

```{r, results = 'asis'}

res <- list()

for (run1 in runs) {
    cat('## ', run1, '{.tabset .tabset-pills} \n\n')
    
    for (run2 in setdiff(runs, run1)) {
        
        cat('### ', run2, '{.tabset .tabset-pills} \n\n')
    
        r1 <- readRDS(file.path(params$clustering_dir, run1))
        r2 <- readRDS(file.path(params$clustering_dir, run2))

        r1.id <- dirname(paste0(".", run1))
        r2.id <- dirname(paste0(".", run2))

        for (metric in c('seconds', 'max_rss', 'max_vms', 'max_uss', 'max_pss', 'io_in', 'io_out', 'mean_load', 'cpu_time')) {
            cat('### ', metric, '\n\n')

            fd <- r1 %>% select(data, method, metric) %>% 
            full_join(r2 %>% select(data, method, metric),
                      by = c("data", "method"), 
                      suffix = c(r1.id, r2.id))

            print(ggplot(fd, aes(x=.data[[paste0(metric, r1.id)]],
                                 y=.data[[paste0(metric, r2.id)]],
                                 colour = data)) +
                  geom_point(size = 3) +
                  geom_abline() +
                  theme(legend.position = "none") +
                  facet_wrap(~method, scales = "free") +
                  theme(aspect.ratio=1))
            
        }
        
        cat('\n\n')
    }
}

```
